//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggieCreationsConsoleApplication.DoggieCreationsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="DoggieCreationsServiceReference.DoggieCreationsServiceSoap")]
    public interface DoggieCreationsServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HelloWorld", ReplyAction="*")]
        DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponse HelloWorld(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponse> HelloWorldAsync(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name insertStringHere from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/VertaalAllesMaar", ReplyAction="*")]
        DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponse VertaalAllesMaar(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/VertaalAllesMaar", ReplyAction="*")]
        System.Threading.Tasks.Task<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponse> VertaalAllesMaarAsync(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://localhost/", Order=0)]
        public DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://localhost/", Order=0)]
        public DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VertaalAllesMaarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VertaalAllesMaar", Namespace="http://localhost/", Order=0)]
        public DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequestBody Body;
        
        public VertaalAllesMaarRequest() {
        }
        
        public VertaalAllesMaarRequest(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class VertaalAllesMaarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertStringHere;
        
        public VertaalAllesMaarRequestBody() {
        }
        
        public VertaalAllesMaarRequestBody(string insertStringHere) {
            this.insertStringHere = insertStringHere;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VertaalAllesMaarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VertaalAllesMaarResponse", Namespace="http://localhost/", Order=0)]
        public DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponseBody Body;
        
        public VertaalAllesMaarResponse() {
        }
        
        public VertaalAllesMaarResponse(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class VertaalAllesMaarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VertaalAllesMaarResult;
        
        public VertaalAllesMaarResponseBody() {
        }
        
        public VertaalAllesMaarResponseBody(string VertaalAllesMaarResult) {
            this.VertaalAllesMaarResult = VertaalAllesMaarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoggieCreationsServiceSoapChannel : DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoggieCreationsServiceSoapClient : System.ServiceModel.ClientBase<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap>, DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap {
        
        public DoggieCreationsServiceSoapClient() {
        }
        
        public DoggieCreationsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoggieCreationsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoggieCreationsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoggieCreationsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponse DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap.HelloWorld(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest inValue = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest();
            inValue.Body = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequestBody();
            DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponse retVal = ((DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponse> DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap.HelloWorldAsync(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldResponse> HelloWorldAsync() {
            DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest inValue = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequest();
            inValue.Body = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.HelloWorldRequestBody();
            return ((DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponse DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap.VertaalAllesMaar(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest request) {
            return base.Channel.VertaalAllesMaar(request);
        }
        
        public string VertaalAllesMaar(string insertStringHere) {
            DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest inValue = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest();
            inValue.Body = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequestBody();
            inValue.Body.insertStringHere = insertStringHere;
            DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponse retVal = ((DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap)(this)).VertaalAllesMaar(inValue);
            return retVal.Body.VertaalAllesMaarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponse> DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap.VertaalAllesMaarAsync(DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest request) {
            return base.Channel.VertaalAllesMaarAsync(request);
        }
        
        public System.Threading.Tasks.Task<DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarResponse> VertaalAllesMaarAsync(string insertStringHere) {
            DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest inValue = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequest();
            inValue.Body = new DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.VertaalAllesMaarRequestBody();
            inValue.Body.insertStringHere = insertStringHere;
            return ((DoggieCreationsConsoleApplication.DoggieCreationsServiceReference.DoggieCreationsServiceSoap)(this)).VertaalAllesMaarAsync(inValue);
        }
    }
}
